### ISSUE TITLE
AVLTree BalanceAfterInsert() has misleading variable name

### ISSUE THREAD

**Issue by vpsoftpro** [phishman3579/java-algorithms-implementation#10]
![image](https://cloud.githubusercontent.com/assets/6687729/9694392/24195170-530d-11e5-846a-fb02032426fa.png)

AVLNode<T> parent  - is actually always a left or a right child of variable node.

**Comment by phishman3579** [comment]
Good catch, I've updated the code.

**Comment by vpsoftpro** [comment]
Thanks, love the algo repo. Keep up the good work.
