### ISSUE TITLE
XYZpoint from latitude/longitude

### ISSUE THREAD

**Issue by hoerup** [phishman3579/java-algorithms-implementation#11]
It would be most helpfull if the KdTree.XYZPoint included the math for mapping a latitude/longitude pair into the 3 dimensional XYZpoint.

I think it is something along the line of

    point[0] = cos(toRadians(latitude)) * cos(toRadians(longitude));
    point[1] = cos(toRadians(latitude)) * sin(toRadians(longitude));
    point[2] = sin(toRadians(latitude));

**Comment by phishman3579** [comment]
Sorry but it gets a bit more complicated to get true XYZ from lat/lon. see:
http://stackoverflow.com/questions/1185408/converting-from-longitude-latitude-to-cartesian-coordinates

**Comment by phishman3579** [comment]
@hoerup I added a new XYZPoint(double lat, double lon) constructor given clarification that it doesn't take curvature of the earth into consideration.
