### ISSUE TITLE
want to add DFS

### ISSUE THREAD

**Issue by jsroyal** [phishman3579/java-algorithms-implementation#38]
Hey! @mciancia 
Can I contribute your repo because I saw you have missed some graph part?
DFS and BFS which is standard agos.

**Comment by phishman3579** [comment]
DFS and BFS would be good addition to the Graph class, just make sure it can handle a graph with cycles.

**Comment by jsroyal** [comment]
I implemented main functionality which is given the adjacency matrix Z and given the root element you will get the Depth First Traversal path. Yes, it will be the handle of cycles.
