### ISSUE TITLE
Readme.md file need to more better structure 

### ISSUE THREAD

**Issue by jsroyal** [phishman3579/java-algorithms-implementation#40]
Hi!, 
I'm seeing here in readme file it has very good content but needs to more organize way.
Likes : 
 
             1. Contents list
            2.  Add relative link to direct code in readme.md
           3. Remove extra folder from repo
           4. Add contribute.md file
           5. Add PULL_REQUEST_TEMPLETE.md
           6. Add License 
Would you like to help ?
Yes!  :)

**Comment by phishman3579** [comment]
Sure, if you have some good ideas then send a merge request and I'll review it.

**Comment by jsroyal** [comment]
@phishman3579 Yes Plesae do some review #41 and make readme file upto date.

**Comment by jsroyal** [comment]
I did complete work and sent PR so please go review it #41 
So now I'm closing this issue.
Thanks
