### ISSUE TITLE
Is there a Ternary Search Tree?

### ISSUE THREAD

**Issue by isapir** [phishman3579/java-algorithms-implementation#60]
Hello,

Is there a Ternary Search Tree implementation here by a different name?  

I tried to look for `TST` or `Ternary` and didn't see one.  Was wondering if it appears under a different name.

Thank you.

**Comment by phishman3579** [comment]
No there isn't one, yet. It's been on my todo list for a while now.

-Justin

**Comment by phishman3579** [comment]
@isapir I've added my first pass at a ternary search tree. Update your repository.

https://github.com/phishman3579/java-algorithms-implementation/blob/master/src/com/jwetherell/algorithms/data_structures/TernarySearchTree.java
