### ISSUE TITLE
Radial search for KdTree

### ISSUE THREAD

**Issue by uburoiubu** [phishman3579/java-algorithms-implementation#96]
Thanks for algorithms. 

I have a question concerning `KdTree`. Would there be a lot of changes to make to implement _radial search_?

I came up with the following solution, but this does not work correctly (something is definetely wrong with `examined` collection):

https://gist.github.com/uburoiubu/c09dd8df5a9f739b0d16f400df76da6a

**Comment by phishman3579** [comment]
Please send an email or hit the forum for these types of questions.
